# Generated by Django 4.2.9 on 2026-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_documents/%Y/%m/%d/', verbose_name='File lưu trữ')),
                ('original_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('extension', models.CharField(max_length=20, verbose_name='Đuôi file')),
                ('category', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document (.docx / .doc)'), ('xlsx', 'Excel / CSV (.xlsx / .csv)'), ('pptx', 'PowerPoint (.pptx / .ppt)'), ('text', 'Text / Code / Log (.txt / .md / .json)'), ('image', 'Hình ảnh / Sơ đồ (.png / .jpg / .webp)'), ('other', 'Định dạng khác')], default='other', max_length=20, verbose_name='Phân loại')),
                ('file_size', models.BigIntegerField(verbose_name='Kích thước (Bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả tài liệu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu File',
                'verbose_name_plural': 'Danh sách Tài liệu File',
                'db_table': 'documents_file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
