# Generated by Django 4.2.9 on 2026-09-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='extracted_chunks_count',
            field=models.IntegerField(default=0, verbose_name='Số lượng Chunks'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='extracted_json',
            field=models.TextField(blank=True, null=True, verbose_name='Dữ liệu Layout JSON'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_extracted',
            field=models.BooleanField(default=False, verbose_name='Đã trích xuất LayoutLM (Text + Ảnh)'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_vector_indexed',
            field=models.BooleanField(default=False, verbose_name='Đã lưu vào Vector DB (Qdrant)'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='vector_points_count',
            field=models.IntegerField(default=0, verbose_name='Số lượng Vector Points'),
        ),
    ]
