# Generated by Django 5.2.15 on 2026-06-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User ID')),
                ('company_id', models.BigIntegerField(blank=True, null=True, verbose_name='Company ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('resource', models.CharField(max_length=255, verbose_name='Resource')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Access Audit',
                'verbose_name_plural': 'Access Audits',
            },
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('block_number', models.BigIntegerField(verbose_name='Block Number')),
                ('tx_hash', models.CharField(max_length=255, verbose_name='Transaction Hash')),
                ('payload', models.TextField(verbose_name='Event Payload')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Blockchain Event',
                'verbose_name_plural': 'Blockchain Events',
            },
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.BigIntegerField(verbose_name='Version ID')),
                ('verify_time', models.DateTimeField(auto_now_add=True, verbose_name='Verification Time')),
                ('verify_result', models.BooleanField(verbose_name='Verification Result')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Verification History',
                'verbose_name_plural': 'Verification Histories',
            },
        ),
        migrations.RemoveField(
            model_name='blockchainaudit',
            name='event_data',
        ),
        migrations.RemoveField(
            model_name='blockchainaudit',
            name='event_type',
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='action',
            field=models.CharField(default='Hash Generated', max_length=100, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='after_state',
            field=models.TextField(blank=True, null=True, verbose_name='After State'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='before_state',
            field=models.TextField(blank=True, null=True, verbose_name='Before State'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='company_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Company ID'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='resource',
            field=models.CharField(default='UNKNOWN', max_length=255, verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='blockchainaudit',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='chaincode_name',
            field=models.CharField(default='ContractVerifyChaincode', max_length=100, verbose_name='Chaincode Name'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='channel_name',
            field=models.CharField(default='contracts-channel', max_length=100, verbose_name='Channel Name'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='confirmation_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Confirmation Time (s)'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='endorser',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endorser'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='fabric_tx_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabric Transaction ID'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='latency',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Latency (s)'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='tx_type',
            field=models.CharField(default='INVOKE', max_length=50, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='hash_version',
            field=models.IntegerField(default=1, verbose_name='Hash Version'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Merkle Root'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Previous Hash'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='hashproof',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='encrypt_algorithm',
            field=models.CharField(default='AES-256-GCM', max_length=50, verbose_name='Encryption Algorithm'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expired At'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='key_type',
            field=models.CharField(default='RSA', max_length=50, verbose_name='Key Type'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='kms_uri',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='KMS URI'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='sign_algorithm',
            field=models.CharField(default='RSASSA-PKCS1-v1_5-SHA256', max_length=50, verbose_name='Signing Algorithm'),
        ),
        migrations.AddField(
            model_name='signaturecertificate',
            name='certificate_pem',
            field=models.TextField(blank=True, null=True, verbose_name='Certificate PEM'),
        ),
        migrations.AddField(
            model_name='signaturecertificate',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='signaturecertificate',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='Revoked'),
        ),
        migrations.AddField(
            model_name='signaturecertificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revoked At'),
        ),
        migrations.AddField(
            model_name='signaturecertificate',
            name='signature_algorithm',
            field=models.CharField(default='SHA256withRSA', max_length=50, verbose_name='Signature Algorithm'),
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(verbose_name='Signature Value')),
                ('algorithm', models.CharField(default='SHA256withRSA', max_length=50, verbose_name='Signing Algorithm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='blockchain.signaturecertificate', verbose_name='Certificate')),
                ('hashproof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='blockchain.hashproof', verbose_name='Hash Proof')),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
            },
        ),
    ]
