# Generated by Django 5.2.15 on 2026-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_accessaudit_blockchainevent_verificationhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessAudit',
        ),
        migrations.RemoveField(
            model_name='blockchainaudit',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='BlockchainEvent',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='network',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='network',
        ),
        migrations.RemoveField(
            model_name='blockchainnode',
            name='network',
        ),
        migrations.DeleteModel(
            name='KeyManagement',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='smart_contract',
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='network_name',
            field=models.CharField(default='Hyperledger Fabric', max_length=100, verbose_name='Network Name'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='smart_contract_name',
            field=models.CharField(default='ContractVerifyChaincode', max_length=100, verbose_name='Smart Contract Name'),
        ),
        migrations.DeleteModel(
            name='BlockchainAudit',
        ),
        migrations.DeleteModel(
            name='BlockchainNetwork',
        ),
        migrations.DeleteModel(
            name='BlockchainNode',
        ),
        migrations.DeleteModel(
            name='SmartContract',
        ),
    ]
