# Generated by Django 5.2.15 on 2026-06-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_delete_accessaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100, verbose_name='Network Name')),
                ('chain_type', models.CharField(max_length=50, verbose_name='Chain Type')),
                ('rpc_endpoint', models.CharField(max_length=255, verbose_name='RPC Endpoint')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
            },
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='network_name',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='smart_contract_name',
        ),
        migrations.CreateModel(
            name='BlockchainAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User ID')),
                ('company_id', models.BigIntegerField(blank=True, null=True, verbose_name='Company ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address')),
                ('action', models.CharField(default='Hash Generated', max_length=100, verbose_name='Action')),
                ('resource', models.CharField(default='UNKNOWN', max_length=255, verbose_name='Resource')),
                ('before_state', models.TextField(blank=True, null=True, verbose_name='Before State')),
                ('after_state', models.TextField(blank=True, null=True, verbose_name='After State')),
                ('status', models.CharField(default='SUCCESS', max_length=50, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='blockchain.blockchaintransaction', verbose_name='Blockchain Transaction')),
            ],
            options={
                'verbose_name': 'Blockchain Audit',
                'verbose_name_plural': 'Blockchain Audits',
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.blockchainnetwork', verbose_name='Blockchain Network'),
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, verbose_name='Contract Address')),
                ('contract_name', models.CharField(max_length=100, verbose_name='Contract Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('deployed_at', models.DateTimeField(verbose_name='Deployed At')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='blockchain.blockchainnetwork', verbose_name='Blockchain Network')),
            ],
            options={
                'verbose_name': 'Smart Contract',
                'verbose_name_plural': 'Smart Contracts',
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='smart_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blockchain.smartcontract', verbose_name='Smart Contract'),
        ),
    ]
