# Generated by Django 5.0.14 on 2026-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_blockchaintransaction_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignature',
            name='block_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Block Hash'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Block Number'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Hash'),
        ),
    ]
