# Generated by Django 5.0.14 on 2026-06-19 09:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=50, unique=True, verbose_name='Contract Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Contract Value')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ANALYZING', 'Analyzing'), ('ANALYZED', 'Analyzed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=255, unique=True, verbose_name='Risk Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('severity_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20, verbose_name='Severity Level')),
            ],
            options={
                'verbose_name': 'Risk Definition',
                'verbose_name_plural': 'Risk Definitions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EXPERT', 'Expert'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('target_model', models.CharField(max_length=100, verbose_name='Target Model')),
                ('target_id', models.BigIntegerField(verbose_name='Target ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_title', models.CharField(max_length=255, verbose_name='Clause Title')),
                ('clause_content', models.TextField(verbose_name='Clause Content')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Clause',
                'verbose_name_plural': 'Clauses',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Overall Score')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, verbose_name='File Path')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Contract File',
                'verbose_name_plural': 'Contract Files',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('final_risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, verbose_name='Final Risk Level')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Reviewed At')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contracts.aianalysis', verbose_name='AI Analysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Expert Review',
                'verbose_name_plural': 'Expert Reviews',
            },
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20, verbose_name='Risk Level')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recommendation')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='contracts.aianalysis', verbose_name='AI Analysis')),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='contracts.clause', verbose_name='Associated Clause')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='contracts.risk', verbose_name='Risk Category')),
            ],
            options={
                'verbose_name': 'Risk Finding',
                'verbose_name_plural': 'Risk Findings',
            },
        ),
    ]
