# Generated by Django 5.0.14 on 2026-06-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

user_role_mapping = {}

def save_user_roles(apps, schema_editor):
    User = apps.get_model('contracts', 'User')
    Role = apps.get_model('contracts', 'Role')
    
    # Ensure default roles exist
    Role.objects.get_or_create(role_name='ADMIN', defaults={'description': 'Administrator'})
    Role.objects.get_or_create(role_name='EXPERT', defaults={'description': 'AI Assessment Expert'})
    Role.objects.get_or_create(role_name='VIEWER', defaults={'description': 'Viewer Only'})

    global user_role_mapping
    for user in User.objects.all():
        if user.role:
            user_role_mapping[user.id] = str(user.role).upper()
            
    # Drop NOT NULL constraint on role column so we can set it to NULL
    schema_editor.execute("ALTER TABLE contracts_user ALTER COLUMN role DROP NOT NULL")
    
    # Set role to null so the AlterField operation doesn't crash on type casting
    User.objects.update(role=None)

def restore_user_roles(apps, schema_editor):
    User = apps.get_model('contracts', 'User')
    Role = apps.get_model('contracts', 'Role')
    
    roles = {r.role_name.upper(): r for r in Role.objects.all()}
    
    global user_role_mapping
    for user_id, role_name in user_role_mapping.items():
        role_obj = roles.get(role_name)
        if not role_obj:
            # fallback to VIEWER
            role_obj = roles.get('VIEWER')
        if role_obj:
            User.objects.filter(id=user_id).update(role=role_obj)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('tax_code', models.CharField(max_length=50, verbose_name='Tax Code')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=100, unique=True, verbose_name='Permission Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='clause',
            name='clause_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clause Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contracts.company', verbose_name='Company'),
        ),
        migrations.CreateModel(
            name='ContractContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=100, verbose_name='Context Type')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('content', models.TextField(verbose_name='Content')),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Relevance Score')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='contracts.contractversion', verbose_name='Contract Version')),
            ],
            options={
                'verbose_name': 'Contract Context',
                'verbose_name_plural': 'Contract Contexts',
            },
        ),
        migrations.CreateModel(
            name='ContextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(max_length=255, verbose_name='Vector ID')),
                ('embedding_model', models.CharField(max_length=100, verbose_name='Embedding Model')),
                ('context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='contracts.contractcontext', verbose_name='Contract Context')),
            ],
            options={
                'verbose_name': 'Context Embedding',
                'verbose_name_plural': 'Context Embeddings',
            },
        ),
        migrations.AddField(
            model_name='clause',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='contracts.contractcontext', verbose_name='Contract Context'),
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255, verbose_name='Party Name')),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Code')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('party_type', models.CharField(max_length=100, verbose_name='Party Type')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Contract Party',
                'verbose_name_plural': 'Contract Parties',
            },
        ),
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('entity_value', models.TextField(verbose_name='Entity Value')),
                ('normalized_value', models.TextField(blank=True, null=True, verbose_name='Normalized Value')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Confidence Score')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_entities', to='contracts.clause', verbose_name='Clause')),
            ],
            options={
                'verbose_name': 'Extracted Entity',
                'verbose_name_plural': 'Extracted Entities',
            },
        ),
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_alias', models.CharField(max_length=255, verbose_name='Key Alias')),
                ('key_provider', models.CharField(max_length=100, verbose_name='Key Provider')),
                ('key_reference', models.CharField(max_length=512, verbose_name='Key Reference')),
                ('algorithm', models.CharField(max_length=100, verbose_name='Algorithm')),
                ('key_version', models.IntegerField(default=1, verbose_name='Key Version')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='Rotated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='contracts.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Key Management',
                'verbose_name_plural': 'Key Managements',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='contracts.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RunPython(save_user_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contracts.role', verbose_name='Role'),
        ),
        migrations.RunPython(restore_user_roles),
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='contracts.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=255, verbose_name='Workflow Name')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='contracts.contractversion', verbose_name='Contract Version')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(verbose_name='Step Order')),
                ('step_name', models.CharField(max_length=255, verbose_name='Step Name')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='contracts.role', verbose_name='Required Role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contracts.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_hash', models.CharField(max_length=512, verbose_name='Signature Hash')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Signed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='contracts.keymanagement', verbose_name='Signing Key')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.workflowstep', verbose_name='Workflow Step')),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.workflowstep', verbose_name='Workflow Step')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
    ]
