# Generated by Django 5.0.14 on 2026-06-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_company_permission_tag_clause_clause_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100, verbose_name='Network Name')),
                ('chain_type', models.CharField(max_length=50, verbose_name='Chain Type')),
                ('rpc_endpoint', models.CharField(max_length=255, verbose_name='RPC Endpoint')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
            },
        ),
        migrations.CreateModel(
            name='BlockchainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100, verbose_name='Node Name')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='contracts.blockchainnetwork', verbose_name='Blockchain Network')),
            ],
            options={
                'verbose_name': 'Blockchain Node',
                'verbose_name_plural': 'Blockchain Nodes',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=255, unique=True, verbose_name='Transaction Hash')),
                ('block_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Block Hash')),
                ('block_number', models.BigIntegerField(blank=True, null=True, verbose_name='Block Number')),
                ('gas_fee', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='Gas Fee')),
                ('status', models.CharField(default='PENDING', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contracts.blockchainnetwork', verbose_name='Blockchain Network')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
            },
        ),
        migrations.CreateModel(
            name='BlockchainAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('event_data', models.TextField(verbose_name='Event Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='contracts.blockchaintransaction', verbose_name='Blockchain Transaction')),
            ],
            options={
                'verbose_name': 'Blockchain Audit',
                'verbose_name_plural': 'Blockchain Audits',
            },
        ),
        migrations.CreateModel(
            name='HashProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_algorithm', models.CharField(default='SHA-256', max_length=50, verbose_name='Hash Algorithm')),
                ('document_hash', models.CharField(max_length=64, verbose_name='Document Hash')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hash_proof', to='contracts.contractversion', verbose_name='Contract Version')),
            ],
            options={
                'verbose_name': 'Hash Proof',
                'verbose_name_plural': 'Hash Proofs',
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contracts.hashproof', verbose_name='Hash Proof'),
        ),
        migrations.CreateModel(
            name='SignatureCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('issuer', models.CharField(max_length=255, verbose_name='Issuer')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Signature Certificate',
                'verbose_name_plural': 'Signature Certificates',
            },
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature', to='contracts.signaturecertificate', verbose_name='Signature Certificate'),
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, verbose_name='Contract Address')),
                ('contract_name', models.CharField(max_length=100, verbose_name='Contract Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('deployed_at', models.DateTimeField(verbose_name='Deployed At')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='contracts.blockchainnetwork', verbose_name='Blockchain Network')),
            ],
            options={
                'verbose_name': 'Smart Contract',
                'verbose_name_plural': 'Smart Contracts',
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='smart_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contracts.smartcontract', verbose_name='Smart Contract'),
        ),
    ]
