# Generated by Django 5.0.14 on 2026-06-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_blockchainnetwork_blockchainnode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainnode',
            name='network',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='network',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='network',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='smart_contract',
        ),
        migrations.RemoveField(
            model_name='hashproof',
            name='version',
        ),
        migrations.RemoveField(
            model_name='signaturecertificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitalsignature',
            name='certificate',
        ),
        migrations.DeleteModel(
            name='BlockchainAudit',
        ),
        migrations.DeleteModel(
            name='BlockchainNode',
        ),
        migrations.DeleteModel(
            name='BlockchainNetwork',
        ),
        migrations.DeleteModel(
            name='BlockchainTransaction',
        ),
        migrations.DeleteModel(
            name='SmartContract',
        ),
        migrations.DeleteModel(
            name='HashProof',
        ),
        migrations.DeleteModel(
            name='SignatureCertificate',
        ),
    ]
