# Generated by Django 5.0.14 on 2026-06-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_blockchainnode_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalsignature',
            name='key',
        ),
        migrations.RemoveField(
            model_name='digitalsignature',
            name='step',
        ),
        migrations.RemoveField(
            model_name='digitalsignature',
            name='user',
        ),
        migrations.RemoveField(
            model_name='keymanagement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='version',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='role',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='DigitalSignature',
        ),
        migrations.DeleteModel(
            name='KeyManagement',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
