# Generated by Django 5.0.14 on 2026-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_digitalsignature_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfinding',
            name='disadvantaged_party',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Disadvantaged Party'),
        ),
    ]
