# Generated by Django 5.0.14 on 2026-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_riskfinding_disadvantaged_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='block_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blockchain Block Hash'),
        ),
        migrations.AddField(
            model_name='company',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Blockchain Block Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blockchain Tx Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='block_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blockchain Block Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Blockchain Block Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blockchain Tx Hash'),
        ),
    ]
