# Generated by Django 4.2.9 on 2026-07-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_extract', '0002_clause_extractedentity'),
        ('contracts', '0007_company_block_hash_company_block_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedentity',
            name='clause',
        ),
        migrations.AlterField(
            model_name='riskfinding',
            name='clause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='ai_extract.clause', verbose_name='Associated Clause'),
        ),
        migrations.DeleteModel(
            name='Clause',
        ),
        migrations.DeleteModel(
            name='ExtractedEntity',
        ),
    ]
