# Generated by Django 5.0.14 on 2026-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_remove_extractedentity_clause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='payload',
            field=models.TextField(blank=True, null=True, verbose_name='Request Payload'),
        ),
    ]
