from django.db import models

class ContractSummary(models.Model):
    """
    Executive summary generated by Kaggle Qwen AI for a contract version.
    Maps to: POST /api/v1/summarize on kaggle_qwen_service.
    """
    version = models.OneToOneField(
        "contracts.ContractVersion",
        on_delete=models.CASCADE,
        related_name="ai_summary",
        verbose_name="Contract Version",
    )
    summary = models.TextField(verbose_name="AI-Generated Summary")
    model_id = models.CharField(
        max_length=200,
        default="phamthanhfd/contract-analysis-qwen2.5-3b",
        verbose_name="Model ID",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Generated At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        verbose_name = "Contract Summary"
        verbose_name_plural = "Contract Summaries"

    def __str__(self):
        return f"Summary – {self.version.contract.contract_code} v{self.version.version_number}"

    @property
    def contract(self):
        return self.version.contract


class Clause(models.Model):
    version = models.ForeignKey(
        "contracts.ContractVersion", 
        on_delete=models.CASCADE, 
        related_name='ai_extract_clauses', 
        verbose_name="Contract Version"
    )
    context = models.ForeignKey(
        "contracts.ContractContext", 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='ai_extract_clauses', 
        verbose_name="Contract Context"
    )
    clause_type = models.CharField(max_length=100, blank=True, null=True, verbose_name="Clause Type")
    clause_title = models.CharField(max_length=255, verbose_name="Clause Title")
    clause_content = models.TextField(verbose_name="Clause Content")

    class Meta:
        verbose_name = 'Clause'
        verbose_name_plural = 'Clauses'

    def __str__(self):
        return f"{self.clause_title} (v{self.version.version_number})"

    @property
    def contract(self):
        return self.version.contract


class ExtractedEntity(models.Model):
    clause = models.ForeignKey(
        Clause, 
        on_delete=models.CASCADE, 
        related_name='ai_extract_entities', 
        verbose_name="Clause"
    )
    entity_type = models.CharField(max_length=100, verbose_name="Entity Type")
    entity_value = models.TextField(verbose_name="Entity Value")
    normalized_value = models.TextField(blank=True, null=True, verbose_name="Normalized Value")
    confidence_score = models.DecimalField(max_digits=5, decimal_places=2, default=0.0, verbose_name="Confidence Score")

    class Meta:
        verbose_name = 'Extracted Entity'
        verbose_name_plural = 'Extracted Entities'

    def __str__(self):
        return f"{self.entity_type}: {self.entity_value[:30]}"
