from django.db import models
from contracts.models import ContractVersion


class ContractSummary(models.Model):
    """
    Executive summary generated by Kaggle Qwen AI for a contract version.
    Maps to: POST /api/v1/summarize on kaggle_qwen_service.
    """
    version = models.OneToOneField(
        ContractVersion,
        on_delete=models.CASCADE,
        related_name="ai_summary",
        verbose_name="Contract Version",
    )
    summary = models.TextField(verbose_name="AI-Generated Summary")
    model_id = models.CharField(
        max_length=200,
        default="phamthanhfd/contract-analysis-qwen2.5-3b",
        verbose_name="Model ID",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Generated At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        verbose_name = "Contract Summary"
        verbose_name_plural = "Contract Summaries"

    def __str__(self):
        return f"Summary – {self.version.contract.contract_code} v{self.version.version_number}"

    @property
    def contract(self):
        return self.version.contract
