# Generated by Django 4.2.9 on 2026-09-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(default='DOC001', max_length=64, unique=True, verbose_name='Mã tài liệu')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tài liệu')),
                ('doc_type', models.CharField(choices=[('SOP', 'Standard Operating Procedure (SOP)'), ('MANUAL', 'Cẩm nang vận hành / Sách hướng dẫn'), ('DRAWING', 'Bản vẽ kỹ thuật 2D / 3D CAD'), ('CATALOG', 'Catalog thiết bị / Bảng thông số'), ('OTHER', 'Tài liệu khác')], default='SOP', max_length=20, verbose_name='Loại tài liệu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả tóm tắt')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='File lưu trữ')),
                ('language', models.CharField(default='Japanese/English/Vietnamese', max_length=64, verbose_name='Ngôn ngữ')),
                ('status', models.CharField(default='PROCESSED', max_length=30, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_code', models.CharField(default='EXP001', max_length=64, unique=True, verbose_name='Mã chuyên gia')),
                ('name', models.CharField(max_length=128, verbose_name='Họ tên chuyên gia')),
                ('department', models.CharField(default='Bảo trì Cơ điện (Maintenance)', max_length=128, verbose_name='Phòng ban')),
                ('position', models.CharField(default='Senior Line Master', max_length=128, verbose_name='Chức vụ')),
                ('experience_years', models.IntegerField(default=10, verbose_name='Số năm kinh nghiệm')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả năng lực chuyên môn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi kỹ sư')),
                ('answer', models.TextField(verbose_name='Câu trả lời của AI')),
                ('rating', models.IntegerField(default=5, verbose_name='Đánh giá sao (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Góp ý của kỹ sư')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_code', models.CharField(default='INT-001', max_length=64, unique=True, verbose_name='Mã phiên phỏng vấn')),
                ('topic', models.CharField(max_length=255, verbose_name='Chủ đề trích xuất tri thức')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang phỏng vấn'), ('COMPLETED', 'Đã hoàn thành'), ('CONVERTED_TO_KNOWLEDGE', 'Đã chuyển đổi thành Tri thức')], default='ACTIVE', max_length=30, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.expert', verbose_name='Chuyên gia được phỏng vấn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi chưa có đủ căn cứ trả lời')),
                ('reason', models.TextField(default='Không tìm thấy SOP chính thức hoặc bằng chứng đủ mạnh', verbose_name='Lý do phát hiện')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phỏng vấn'), ('IN_PROGRESS', 'Đang thu thập'), ('RESOLVED', 'Đã giải quyết & Tạo Knowledge')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gaps', to='core.expert', verbose_name='Chuyên gia được đề xuất')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_code', models.CharField(default='K001', max_length=64, unique=True, verbose_name='Mã tri thức')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tri thức')),
                ('content', models.TextField(verbose_name='Nội dung quy tắc / tri thức')),
                ('knowledge_type', models.CharField(choices=[('RULE', 'Quy tắc phán đoán / Xử lý lỗi'), ('SOP', 'Quy trình vận hành bổ sung'), ('EXCEPTION', 'Quy tắc xử lý ngoại lệ an toàn')], default='RULE', max_length=20, verbose_name='Loại tri thức')),
                ('source_type', models.CharField(default='EXPERT', max_length=50, verbose_name='Nguồn gốc (EXPERT / DOCUMENT)')),
                ('source_id', models.CharField(default='EXP001', max_length=64, verbose_name='Mã nguồn (Expert ID hoặc Doc ID)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt (Active)'), ('REJECTED', 'Đã từ chối')], default='APPROVED', max_length=20, verbose_name='Trạng thái phê duyệt')),
                ('confidence', models.FloatField(default=0.92, verbose_name='Độ tin cậy (Confidence Score)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rules', to='core.expert', verbose_name='Chuyên gia phê duyệt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('ai', 'Trợ lý AI (Interviewer)'), ('expert', 'Chuyên gia (Expert)')], default='ai', max_length=20, verbose_name='Người gửi')),
                ('message', models.TextField(verbose_name='Nội dung thông điệp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.interview', verbose_name='Phiên phỏng vấn')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=128, verbose_name='Tên kỹ năng')),
                ('level', models.IntegerField(default=5, verbose_name='Mức độ thành thạo (1-5)')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.expert', verbose_name='Chuyên gia')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Số trang')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='pages/%Y/%m/', verbose_name='Ảnh trang PDF')),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='Văn bản bóc tách')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.document', verbose_name='Tài liệu')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung trích xuất')),
                ('chunk_type', models.CharField(choices=[('text', 'Đoạn văn bản'), ('table', 'Bảng thông số'), ('figure', 'Bản vẽ / Sơ đồ CAD'), ('header', 'Tiêu đề mục')], default='text', max_length=20, verbose_name='Loại chunk')),
                ('bbox_json', models.TextField(default='[]', verbose_name='Tọa độ BBox [ymin, xmin, ymax, xmax]')),
                ('embedding_json', models.TextField(blank=True, null=True, verbose_name='Vector Embedding JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.documentpage', verbose_name='Trang tài liệu')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(default='CASE-101', max_length=64, unique=True, verbose_name='Mã ca sự cố')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề sự cố')),
                ('machine', models.CharField(max_length=128, verbose_name='Thiết bị / Cụm máy')),
                ('part_code', models.CharField(default='N/A', max_length=64, verbose_name='Mã linh kiện / Phụ tùng')),
                ('symptom', models.TextField(verbose_name='Triệu chứng lỗi')),
                ('root_cause', models.TextField(verbose_name='Nguyên nhân gốc rễ')),
                ('solution', models.TextField(verbose_name='Biện pháp xử lý đã thực hiện')),
                ('result', models.CharField(default='Resolved (Đã khắc phục)', max_length=64, verbose_name='Kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.expert', verbose_name='Chuyên gia xử lý')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
