# Generated by Django 4.2.9 on 2026-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='embedding_json',
            field=models.TextField(blank=True, null=True, verbose_name='Vector Embedding JSON'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='embedding_json',
            field=models.TextField(blank=True, null=True, verbose_name='Vector Embedding JSON'),
        ),
    ]
