# Generated by Django 5.2.15 on 2026-06-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(verbose_name='Company ID')),
                ('key_alias', models.CharField(max_length=255, verbose_name='Key Alias')),
                ('key_provider', models.CharField(max_length=100, verbose_name='Key Provider')),
                ('key_reference', models.CharField(max_length=512, verbose_name='Key Reference')),
                ('algorithm', models.CharField(max_length=100, verbose_name='Algorithm')),
                ('key_version', models.IntegerField(default=1, verbose_name='Key Version')),
                ('status', models.CharField(default='ACTIVE', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='Rotated At')),
            ],
            options={
                'verbose_name': 'Key Management',
                'verbose_name_plural': 'Key Managements',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.BigIntegerField(verbose_name='Contract Version ID')),
                ('workflow_name', models.CharField(max_length=255, verbose_name='Workflow Name')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.BigIntegerField(verbose_name='Workflow Step ID')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('signature_hash', models.CharField(max_length=512, verbose_name='Signature Hash')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Signed At')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='workflow.keymanagement', verbose_name='Signing Key')),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(blank=True, null=True, verbose_name='Required Role ID')),
                ('step_order', models.IntegerField(verbose_name='Step Order')),
                ('step_name', models.CharField(max_length=255, verbose_name='Step Name')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow.workflowstep', verbose_name='Workflow Step')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
    ]
