# Generated by Django 5.0.14 on 2026-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='reasons',
            field=models.TextField(blank=True, null=True, verbose_name='AI Recommendation Reasons'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow Type'),
        ),
    ]
