# Generated by Django 4.2.9 on 2026-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflow_reasons_workflow_workflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
