# Generated by Django 4.2.9 on 2026-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignature',
            name='algorithm',
            field=models.CharField(default='SHA256withRSA', max_length=100, verbose_name='Signing Algorithm'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='block_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Block Hash'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Block Number'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabric Transaction Hash'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
    ]
