# Generated by Django 5.0.14 on 2026-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_add_blockchain_fields_to_digitalsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='company_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Company ID'),
        ),
    ]
