# Generated by Django 5.0.14 on 2026-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workflow_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='company_id',
        ),
        migrations.AddField(
            model_name='workflow',
            name='contract_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Code'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='contract_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Contract ID'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='contract_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract Title'),
        ),
    ]
