# Generated by Django 5.0.14 on 2026-08-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_workflow_company_id_workflow_contract_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='contract_code',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='contract_title',
        ),
    ]
