# Generated by Django 4.2.9 on 2026-08-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_remove_workflow_contract_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('dependent_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_on', to='workflow.workflowstep', verbose_name='Dependent Step (Bị nối - Bị khóa)')),
                ('prerequisite_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_for', to='workflow.workflowstep', verbose_name='Prerequisite Step (Nối đến - Phải xong trước)')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflow.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Step Dependency',
                'verbose_name_plural': 'Step Dependencies',
                'unique_together': {('prerequisite_step', 'dependent_step')},
            },
        ),
    ]
