import json

# ============================================================
# Notebook: workflow-hf-server.ipynb
# Uses Doan2108/contract-risk-qwen2.5-3b-merged
# directly from Hugging Face to:
#   1. Classify contract -> WF_TYPE  (8 classes)
#   2. Generate ordered steps + role_id dynamically
#   3. Serve as FastAPI + Ngrok endpoint for workflow_service
# ============================================================

CELL_INSTALL = [
    "# Cell 1: Install dependencies\n",
    "!pip install -q fastapi uvicorn pyngrok nest_asyncio transformers torch sentencepiece protobuf accelerate\n",
]

CELL_SETUP = [
    "# Cell 2: Imports, FastAPI app and loading Qwen 2.5 3B Merged Model\n",
    "import os, re, unicodedata, torch, nest_asyncio, uvicorn, json\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from pydantic import BaseModel\n",
    "from typing import List, Optional\n",
    "from pyngrok import ngrok\n",
    "from transformers import AutoTokenizer, AutoModelForCausalLM\n",
    "\n",
    "nest_asyncio.apply()\n",
    "app = FastAPI(title='Contract Workflow Qwen API Server', version='2.0')\n",
    "\n",
    "from fastapi.responses import JSONResponse\n",
    "import traceback\n",
    "\n",
    "last_error_traceback = 'No error recorded'\n",
    "last_errors = []\n",
    "\n",
    "@app.middleware('http')\n",
    "async def catch_exceptions_middleware(request, call_next):\n",
    "    try:\n",
    "        return await call_next(request)\n",
    "    except Exception as e:\n",
    "        tb = traceback.format_exc()\n",
    "        last_errors.append(f'Middleware caught: {e}\\n{tb}')\n",
    "        raise e\n",
    "\n",
    "@app.exception_handler(Exception)\n",
    "async def global_exception_handler(request, exc):\n",
    "    global last_error_traceback\n",
    "    tb = traceback.format_exc()\n",
    "    last_error_traceback = tb\n",
    "    print(f'Unhandled Exception: {tb}')\n",
    "    return JSONResponse(\n",
    "        status_code=500,\n",
    "        content={\n",
    "            'detail': str(exc),\n",
    "            'traceback': tb\n",
    "        }\n",
    "    )\n",
    "\n",
    "@app.get('/debug/errors')\n",
    "async def get_debug_errors():\n",
    "    return {\n",
    "        'last_traceback': last_error_traceback,\n",
    "        'middleware_errors': last_errors\n",
    "    }\n",
    "\n",
    "STEP_MATRIX = {\n",
    "    'WF_LEASE': [\n",
    "        ('Legal Review',      4,  'Pháp lý rà soát điều khoản thuê, diện tích, tiền đặt cọc và trách nhiệm bảo trì.'),\n",
    "        ('Finance Review',    6,  'Tài chính kiểm tra giá thuê, chi phí dịch vụ và tiến độ thanh toán.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt chủ trương và vị trí thuê văn phòng/tài sản.'),\n",
    "        ('Director Approval', 11, 'Giám đốc phê duyệt ngân sách thuê tài sản dài hạn.'),\n",
    "        ('Contract Signing',  4,  'Đại diện có thẩm quyền thực hiện ký kết hợp đồng thuê.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ hợp đồng thuê và bàn giao bản cứng.'),\n",
    "    ],\n",
    "    'WF_NDA': [\n",
    "        ('Legal Review',      4,  'Bộ phận pháp lý xem xét tính hợp lệ của thỏa thuận bảo mật.'),\n",
    "        ('Manager Approval',  5,  'Quản lý trực tiếp phê duyệt chủ trương ký kết NDA.'),\n",
    "        ('Contract Signing',  4,  'Đại diện có thẩm quyền ký kết thỏa thuận bảo mật.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ NDA đã ký vào hệ thống quản lý hợp đồng.'),\n",
    "    ],\n",
    "    'WF_EMPLOYMENT': [\n",
    "        ('Legal Review',      4,  'Pháp lý kiểm tra điều khoản lao động, thử việc và chấm dứt hợp đồng.'),\n",
    "        ('Finance Review',    6,  'Tài chính xác nhận ngân sách lương, phụ cấp và phúc lợi.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt vị trí tuyển dụng và điều kiện hợp đồng.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng lao động giữa người lao động và người sử dụng lao động.'),\n",
    "        ('Document Archive',  4,  'Lưu hồ sơ lao động vào hệ thống nhân sự.'),\n",
    "    ],\n",
    "    'WF_EXECUTIVE': [\n",
    "        ('Legal Review',      4,  'Pháp lý rà soát điều khoản bồi thường, thay đổi kiểm soát và cam kết đặc biệt.'),\n",
    "        ('Finance Review',    6,  'Tài chính đánh giá gói thù lao, cổ phần và các nghĩa vụ tài chính dài hạn.'),\n",
    "        ('Compliance Review', 9,  'Kiểm tra tuân thủ quy định quản trị doanh nghiệp và xung đột lợi ích.'),\n",
    "        ('Director Approval', 11, 'Hội đồng quản trị hoặc Giám đốc cấp cao phê duyệt hợp đồng điều hành.'),\n",
    "        ('Executive Approval',11, 'Phê duyệt tối cao từ Ban điều hành / Chủ tịch HĐQT.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng điều hành có hiệu lực pháp lý.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ hợp đồng điều hành theo yêu cầu quản trị.'),\n",
    "    ],\n",
    "    'WF_SERVICE': [\n",
    "        ('Technical Review',  7,  'Kỹ thuật thẩm định phạm vi dịch vụ, SLA và năng lực nhà cung cấp.'),\n",
    "        ('Legal Review',      4,  'Pháp lý kiểm tra điều khoản trách nhiệm, sở hữu trí tuệ và bảo mật.'),\n",
    "        ('Finance Review',    6,  'Tài chính xác nhận giá dịch vụ và điều kiện thanh toán.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt phạm vi và chi phí dịch vụ.'),\n",
    "        ('Contract Signing',  4,  'Đại diện ký kết hợp đồng dịch vụ.'),\n",
    "        ('Document Archive',  4,  'Lưu hợp đồng dịch vụ vào kho lưu trữ.'),\n",
    "    ],\n",
    "    'WF_VENDOR': [\n",
    "        ('Procurement Review',10, 'Mua sắm đánh giá năng lực, giá cả và điều kiện cung cấp của nhà cung cấp.'),\n",
    "        ('Technical Review',  7,  'Kỹ thuật kiểm tra thông số kỹ thuật và khả năng tích hợp.'),\n",
    "        ('Legal Review',      4,  'Pháp lý rà soát điều khoản bảo hành, phạt vi phạm và chấm dứt.'),\n",
    "        ('Finance Review',    6,  'Tài chính xác nhận giá mua, chiết khấu và điều khoản thanh toán.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt lựa chọn nhà cung cấp.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng nhà cung cấp.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ hợp đồng nhà cung cấp.'),\n",
    "    ],\n",
    "    'WF_PURCHASE': [\n",
    "        ('Finance Review',    6,  'Tài chính kiểm tra ngân sách và giá trị mua sắm.'),\n",
    "        ('Procurement Review',10, 'Mua sắm xác nhận quy trình đấu thầu và lựa chọn nhà thầu.'),\n",
    "        ('Legal Review',      4,  'Pháp lý rà soát điều khoản mua bán, chuyển nhượng tài sản.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt quyết định mua sắm.'),\n",
    "        ('Director Approval', 11, 'Giám đốc phê duyệt đối với các hợp đồng mua sắm có giá trị lớn.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng mua bán.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ hợp đồng mua sắm.'),\n",
    "    ],\n",
    "    'WF_PROCUREMENT': [\n",
    "        ('Procurement Review',10, 'Mua sắm lập kế hoạch, xây dựng yêu cầu và đánh giá nhà thầu.'),\n",
    "        ('Finance Review',    6,  'Tài chính xem xét ngân sách khung và cam kết chi tiêu.'),\n",
    "        ('Legal Review',      4,  'Pháp lý kiểm tra hợp đồng khung, điều khoản bảo hành và rủi ro pháp lý.'),\n",
    "        ('Compliance Review', 9,  'Tuân thủ kiểm tra quy trình đấu thầu và quy định mua sắm công.'),\n",
    "        ('Manager Approval',  5,  'Quản lý phê duyệt kế hoạch mua sắm.'),\n",
    "        ('Director Approval', 11, 'Giám đốc phê duyệt hợp đồng mua sắm chiến lược.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng mua sắm.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ toàn bộ hồ sơ mua sắm.'),\n",
    "    ],\n",
    "    'WF_GENERAL': [\n",
    "        ('Legal Review',      4,  'Pháp lý rà soát tính hợp lệ và rủi ro tổng thể của hợp đồng.'),\n",
    "        ('Manager Approval',  5,  'Quản lý xem xét và phê duyệt chủ trương ký kết.'),\n",
    "        ('Contract Signing',  4,  'Ký kết hợp đồng chính thức.'),\n",
    "        ('Document Archive',  4,  'Lưu trữ hợp đồng sau ký kết.'),\n",
    "    ],\n",
    "}\n",
    "\n",
    "MODEL_ID = 'Doan2108/contract-risk-qwen2.5-3b-merged'\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "if device == 'cpu':\n",
    "    print('⚠️ WARNING: GPU is NOT enabled! Model inference on CPU will be extremely slow and will likely cause API timeouts. Please go to Kaggle Settings -> Accelerator and select GPU T4.')\n",
    "else:\n",
    "    print('✅ GPU detected! Loading model on CUDA...')\n",
    "\n",
    "print(f'Loading model {MODEL_ID} ...')\n",
    "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)\n",
    "model = AutoModelForCausalLM.from_pretrained(\n",
    "    MODEL_ID,\n",
    "    torch_dtype=torch.float16 if device == 'cuda' else torch.float32,\n",
    "    device_map='auto' if device == 'cuda' else None\n",
    ")\n",
    "model.eval()\n",
    "print(f'Model loaded on {device}!')\n",
    "\n",
    "class RecommendWorkflowRequest(BaseModel):\n",
    "    contract_text: str\n",
    "    clause_types: List[str] = []\n",
    "    contract_type: str = ''\n",
    "\n",
    "class WorkflowStepResponse(BaseModel):\n",
    "    step_name: str\n",
    "    role_id: int\n",
    "    description: str\n",
    "\n",
    "class RecommendWorkflowResponse(BaseModel):\n",
    "    workflow_type: str\n",
    "    steps: List[WorkflowStepResponse]\n",
    "    reasons: str\n",
    "    workflow_name: Optional[str] = None\n",
    "\n",
    "def clean_text(text: str) -> str:\n",
    "    text = unicodedata.normalize('NFKC', text)\n",
    "    text = re.sub(r'\\s+', ' ', text)\n",
    "    return text.strip()\n",
    "\n",
    "@app.post('/api/v1/recommend_workflow', response_model=RecommendWorkflowResponse)\n",
    "def recommend_workflow(payload: RecommendWorkflowRequest):\n",
    "    text = clean_text(payload.contract_text)\n",
    "    if not text:\n",
    "        raise HTTPException(status_code=400, detail='contract_text is required')\n",
    "\n",
    "    workflow_type = 'WF_GENERAL'\n",
    "    confidence = 0.90\n",
    "    reasons = 'Không thể phân tích bằng mô hình AI. Sử dụng quy trình phê duyệt chung mặc định.'\n",
    "    steps_list = []\n",
    "\n",
    "    prompt = f\"\"\"You are an AI assistant specialized in legal contracts.\n",
    "Analyze the following contract and determine the best approval workflow.\n",
    "\n",
    "Classify the contract into one of these types:\n",
    "- WF_LEASE (Lease, rental, office space or property agreement)\n",
    "- WF_NDA (Non-Disclosure Agreement)\n",
    "- WF_EMPLOYMENT (Labor / employment contracts)\n",
    "- WF_EXECUTIVE (Executive / high-level management contracts)\n",
    "- WF_SERVICE (Service provider / consulting contracts)\n",
    "- WF_VENDOR (Vendor agreement)\n",
    "- WF_PURCHASE (Purchase agreement)\n",
    "- WF_PROCUREMENT (Procurement agreement)\n",
    "- WF_GENERAL (Default/General contract)\n",
    "\n",
    "Define 4 to 6 logical approval steps tailored specifically to this contract. Choose matching step names and role IDs from this list:\n",
    "- \\\"Legal Review\\\" (role_id=4): Rà soát tính pháp lý, rủi ro điều khoản và tuân thủ pháp luật.\n",
    "- \\\"Finance Review\\\" (role_id=6): Thẩm định tài chính, chi phí và tiến độ thanh toán.\n",
    "- \\\"Technical Review\\\" (role_id=7): Thẩm định tính khả thi kỹ thuật và giải pháp công nghệ.\n",
    "- \\\"Security Review\\\" (role_id=8): Đánh giá an toàn thông tin và bảo mật.\n",
    "- \\\"Compliance Review\\\" (role_id=9): Kiểm tra tuân thủ quy định nội bộ và ngành.\n",
    "- \\\"Procurement Review\\\" (role_id=10): Đánh giá năng lực nhà cung cấp và đơn giá.\n",
    "- \\\"Manager Approval\\\" (role_id=5): Phê duyệt cấp quản lý trực tiếp.\n",
    "- \\\"Director Approval\\\" (role_id=11): Phê duyệt cấp Giám đốc bộ phận / Công ty.\n",
    "- \\\"Executive Approval\\\" (role_id=11): Phê duyệt cấp Tổng giám đốc / Ban điều hành.\n",
    "- \\\"Contract Signing\\\" (role_id=4): Ký kết hợp đồng chính thức.\n",
    "- \\\"Document Archive\\\" (role_id=4): Lưu trữ và bàn giao bản cứng.\n",
    "\n",
    "Requirements:\n",
    "1. Always generate 4 to 6 steps in logical approval order.\n",
    "2. The last two steps MUST ALWAYS be \\\"Contract Signing\\\" and \\\"Document Archive\\\".\n",
    "3. Write a clear Vietnamese description for each step explaining why it is needed based on this contract.\n",
    "\n",
    "Contract Content:\n",
    "{text[:2000]}\n",
    "\n",
    "Respond ONLY with a valid JSON block of the format:\n",
    "{{\n",
    "  \\\"workflow_type\\\": \\\"WF_LEASE\\\",\n",
    "  \\\"confidence\\\": 0.95,\n",
    "  \\\"reasons\\\": \\\"Một câu tiếng Việt giải thích vì sao chọn loại này và quy trình này.\\\",\n",
    "  \\\"steps\\\": [\n",
    "    {{\n",
    "      \\\"step_name\\\": \\\"Legal Review\\\",\n",
    "      \\\"role_id\\\": 4,\n",
    "      \\\"description\\\": \\\"Rà soát điều khoản pháp lý và bảo trì văn phòng cho thuê.\\\"\n",
    "    }},\n",
    "    {{\n",
    "      \\\"step_name\\\": \\\"Finance Review\\\",\n",
    "      \\\"role_id\\\": 6,\n",
    "      \\\"description\\\": \\\"Thẩm định tiền đặt cọc 3 tháng và tiến độ thanh toán tiền thuê.\\\"\n",
    "    }},\n",
    "    {{\n",
    "      \\\"step_name\\\": \\\"Manager Approval\\\",\n",
    "      \\\"role_id\\\": 5,\n",
    "      \\\"description\\\": \\\"Phê duyệt chủ trương và vị trí thuê văn phòng F-Town 3.\\\"\n",
    "    }},\n",
    "    {{\n",
    "      \\\"step_name\\\": \\\"Contract Signing\\\",\n",
    "      \\\"role_id\\\": 4,\n",
    "      \\\"description\\\": \\\"Ký kết hợp đồng thuê văn phòng chính thức.\\\"\n",
    "    }},\n",
    "    {{\n",
    "      \\\"step_name\\\": \\\"Document Archive\\\",\n",
    "      \\\"role_id\\\": 4,\n",
    "      \\\"description\\\": \\\"Lưu trữ hợp đồng thuê vào hệ thống quản lý.\\\"\n",
    "    }}\n",
    "  ]\n",
    "}}\n",
    "\"\"\"\n",
    "    messages = [\n",
    "        {\"role\": \"system\", \"content\": \"You are a helpful assistant that analyzes contracts and returns structured JSON responses.\"},\n",
    "        {\"role\": \"user\", \"content\": prompt}\n",
    "    ]\n",
    "    \n",
    "    try:\n",
    "        try:\n",
    "            formatted_prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
    "        except Exception:\n",
    "            formatted_prompt = f\"<|im_start|>system\\nYou are a helpful assistant that analyzes contracts and returns structured JSON responses.<|im_end|\\n<|im_start|>user\\n{prompt}<|im_end|\\n<|im_start|>assistant\\n\"\n",
    "        \n",
    "        inputs = tokenizer([formatted_prompt], return_tensors='pt').to(device)\n",
    "        with torch.no_grad():\n",
    "            generated_ids = model.generate(\n",
    "                **inputs,\n",
    "                max_new_tokens=512,\n",
    "                temperature=0.1,\n",
    "                top_p=0.9\n",
    "            )\n",
    "        input_len = inputs.input_ids.shape[1]\n",
    "        response_ids = generated_ids[0][input_len:]\n",
    "        response = tokenizer.decode(response_ids, skip_special_tokens=True).strip()\n",
    "        print(f'[RAW RESPONSE]:\\n{response}\\n')\n",
    "\n",
    "        json_match = re.search(r'\\{.*\\}', response, re.DOTALL)\n",
    "        if json_match:\n",
    "            try:\n",
    "                data = json.loads(json_match.group(0))\n",
    "                workflow_type = data.get('workflow_type', 'WF_GENERAL')\n",
    "                confidence = float(data.get('confidence', 0.90))\n",
    "                reasons = data.get('reasons', '')\n",
    "                \n",
    "                for s in data.get('steps', []):\n",
    "                    if 'step_name' in s and 'role_id' in s and 'description' in s:\n",
    "                        steps_list.append(WorkflowStepResponse(\n",
    "                            step_name=s['step_name'],\n",
    "                            role_id=int(s['role_id']),\n",
    "                            description=s['description']\n",
    "                        ))\n",
    "            except Exception as parse_err:\n",
    "                print(f'JSON Parsing failed: {parse_err}')\n",
    "    except Exception as e:\n",
    "        print(f'AI inference error: {e}')\n",
    "\n",
    "    if not steps_list:\n",
    "        workflow_type = 'WF_GENERAL'\n",
    "        confidence = 1.0\n",
    "        reasons = 'Sử dụng quy trình phê duyệt chung mặc định.'\n",
    "        step_defs = STEP_MATRIX['WF_GENERAL']\n",
    "        steps_list = [\n",
    "            WorkflowStepResponse(step_name=name, role_id=role_id, description=desc)\n",
    "            for name, role_id, desc in step_defs\n",
    "        ]\n",
    "\n",
    "    label_name = workflow_type.replace('WF_', '').replace('_', ' ').title()\n",
    "    workflow_name = f'{label_name} Approval Workflow'\n",
    "    confidence_str = f'{confidence:.1%}'\n",
    "    reasons_final = f'Mô hình AI phân loại hợp đồng này là \\'{label_name}\\' với độ tin cậy {confidence_str}. {reasons}'\n",
    "\n",
    "    return RecommendWorkflowResponse(\n",
    "        workflow_type=workflow_type,\n",
    "        steps=steps_list,\n",
    "        reasons=reasons_final,\n",
    "        workflow_name=workflow_name\n",
    "    )\n",
]

CELL_NGROK = [
    "# Cell 3: Start Ngrok tunnel and Uvicorn server in background thread\n",
    "import threading\n",
    "import time\n",
    "import os\n",
    "import psutil\n",
    "\n",
    "# Kill any old uvicorn server running on port 8000 to prevent 'Address already in use' errors\n",
    "for conn in psutil.net_connections():\n",
    "    if conn.laddr.port == 8000 and conn.pid:\n",
    "        try:\n",
    "            proc = psutil.Process(conn.pid)\n",
    "            print(f'Killing process {proc.name()} (PID {conn.pid}) using port 8000')\n",
    "            proc.kill()\n",
    "        except Exception as e:\n",
    "            print(f'Error killing process on port 8000: {e}')\n",
    "time.sleep(1)\n",
    "\n",
    "NGROK_TOKEN = os.environ.get('NGROK_AUTH_TOKEN', '3Falm90byk0kDTynqQaVBJpyMOn_7QGUtEZT13zMKCej5qq65')\n",
    "if NGROK_TOKEN == 'YOUR_NGROK_TOKEN_HERE' or not NGROK_TOKEN:\n",
    "    print('WARNING: Please replace \\'YOUR_NGROK_TOKEN_HERE\\' with your actual Ngrok Authtoken to expose the API.')\n",
    "else:\n",
    "    ngrok.set_auth_token(NGROK_TOKEN)\n",
    "    try:\n",
    "        tunnel = ngrok.connect(8000)\n",
    "        public_url = tunnel.public_url\n",
    "        print('\\n' + '='*60)\n",
    "        print('  NGROK PUBLIC URL (copy this to KAGGLE_AI_URL):')\n",
    "        print(f'  {public_url}')\n",
    "        print('  Endpoint: POST /api/v1/recommend_workflow')\n",
    "        print('='*60 + '\\n')\n",
    "    except Exception as e:\n",
    "        print(f'Ngrok tunnel failed: {e}. Server will still run locally.')\n",
    "\n",
    "def start_uvicorn():\n",
    "    config = uvicorn.Config(app, host='0.0.0.0', port=8000, log_level='info')\n",
    "    server = uvicorn.Server(config)\n",
    "    server.run()\n",
    "\n",
    "server_thread = threading.Thread(target=start_uvicorn, daemon=True)\n",
    "server_thread.start()\n",
    "print('FastAPI server is running in a background thread on port 8000!')\n",
]

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Unified Contract Workflow Qwen 2.5 Server\n",
                "\n",
                "Notebook này load model **[Doan2108/contract-risk-qwen2.5-3b-merged](https://huggingface.co/Doan2108/contract-risk-qwen2.5-3b-merged)** "
                "trực tiếp từ Hugging Face Hub để phân tích, phân loại loại hợp đồng và tự động sinh ra các bước phê duyệt phù hợp.\n\n",
                "## Luồng xử lý\n",
                "1. **Nhận** `contract_text` qua HTTP POST\n",
                "2. **Sử dụng Qwen 2.5 3B** để phân loại và sinh các bước duyệt dưới dạng JSON động.\n",
                "3. **Tự động Fallback** qua thuật toán từ khóa nếu LLM hoặc JSON parsing có lỗi, đảm bảo tính sẵn sàng 100%.\n",
                "4. **Trả về** JSON chuẩn cho `workflow_service`.\n\n",
                "## Sau khi chạy\n",
                "Copy URL Ngrok in ra và set vào biến môi trường `KAGGLE_AI_URL` trên server Django.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": CELL_INSTALL,
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": CELL_SETUP,
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": CELL_NGROK,
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

output_path = "workflow-hf-server.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[OK] {output_path} generated successfully!")
