# Generated by Django 4.2.9 on 2026-07-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0007_company_block_hash_company_block_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='AI-Generated Summary')),
                ('model_id', models.CharField(default='phamthanhfd/contract-analysis-qwen2.5-3b', max_length=200, verbose_name='Model ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='contracts.contractversion', verbose_name='Contract Version')),
            ],
            options={
                'verbose_name': 'Contract Summary',
                'verbose_name_plural': 'Contract Summaries',
            },
        ),
    ]
