# Generated by Django 4.2.9 on 2026-07-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_company_block_hash_company_block_number_and_more'),
        ('ai_extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clause Type')),
                ('clause_title', models.CharField(max_length=255, verbose_name='Clause Title')),
                ('clause_content', models.TextField(verbose_name='Clause Content')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extract_clauses', to='contracts.contractcontext', verbose_name='Contract Context')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extract_clauses', to='contracts.contractversion', verbose_name='Contract Version')),
            ],
            options={
                'verbose_name': 'Clause',
                'verbose_name_plural': 'Clauses',
            },
        ),
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('entity_value', models.TextField(verbose_name='Entity Value')),
                ('normalized_value', models.TextField(blank=True, null=True, verbose_name='Normalized Value')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Confidence Score')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extract_entities', to='ai_extract.clause', verbose_name='Clause')),
            ],
            options={
                'verbose_name': 'Extracted Entity',
                'verbose_name_plural': 'Extracted Entities',
            },
        ),
    ]
